# Generated by Django 4.0.4 on 2022-05-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sektorea')),
                ('country', models.CharField(max_length=200, verbose_name='Herrialdea')),
                ('ccaa', models.CharField(max_length=200, verbose_name='Autonomi erkidegoa')),
                ('province', models.CharField(max_length=200, verbose_name='Probintzia')),
                ('town', models.CharField(max_length=200, verbose_name='Herria')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Latitudea')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Latitudea')),
                ('description', models.TextField(verbose_name='Deskribapena')),
                ('image1', models.ImageField(upload_to='projects', verbose_name='Irudia 1')),
                ('image2', models.ImageField(upload_to='projects', verbose_name='Irudia 2')),
                ('image3', models.ImageField(upload_to='projects', verbose_name='Irudia 3')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Web helbidea')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Sortze data')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Edizio data')),
            ],
            options={
                'verbose_name': 'Sektorea',
                'verbose_name_plural': 'Sektoreak',
                'ordering': ['-created'],
            },
        ),
    ]
