# Generated by Django 4.0.4 on 2022-05-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_climbingspot_harria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climbingspot',
            name='Harria',
        ),
        migrations.AddField(
            model_name='climbingspot',
            name='stone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Harria'),
        ),
    ]
