# Generated by Django 4.0.4 on 2022-05-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_climbingspot_harria_climbingspot_stone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbingspot',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Deskribapena'),
        ),
    ]
