# Generated by Django 4.0.4 on 2022-05-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_climbingspot_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climbingspot',
            options={'ordering': ['created'], 'verbose_name': 'Sektorea', 'verbose_name_plural': 'Sektoreak'},
        ),
        migrations.AddField(
            model_name='climbingspot',
            name='difficulty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Zailtasuna'),
        ),
        migrations.AlterField(
            model_name='climbingspot',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitudea'),
        ),
    ]
