# Generated by Django 4.0.4 on 2022-05-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_climbingspot_options_climbingspot_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(blank=True, max_length=200, null=True, verbose_name='Herria')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitudea')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitudea')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Sortze data')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Edizio data')),
            ],
            options={
                'verbose_name': 'Eguraldia',
                'verbose_name_plural': 'Eguraldia',
                'ordering': ['created'],
            },
        ),
    ]
