# Generated by Django 4.0.4 on 2022-05-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_camping_delete_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='camping',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Izena'),
        ),
        migrations.AlterField(
            model_name='camping',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Deskribapena'),
        ),
    ]
