# Generated by Django 4.0.4 on 2022-05-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_location_camping_address_camping_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Izena')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Herria')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Deskribapena')),
                ('section', models.CharField(blank=True, max_length=200, null=True, verbose_name='Atala')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Sortze data')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Edizio data')),
            ],
            options={
                'verbose_name': 'Bideoa',
                'verbose_name_plural': 'Bideoak',
                'ordering': ['created'],
            },
        ),
    ]
