# Generated by Django 4.0.4 on 2022-05-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_video_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sektorea')),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='Herrialdea')),
                ('ccaa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Autonomi erkidegoa')),
                ('province', models.CharField(blank=True, max_length=200, null=True, verbose_name='Probintzia')),
                ('town', models.CharField(blank=True, max_length=200, null=True, verbose_name='Herria')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitudea')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitudea')),
                ('stone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Harria')),
                ('difficulty', models.CharField(blank=True, max_length=200, null=True, verbose_name='Zailtasuna')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskribapena')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='Irudia 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='Irudia 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='Irudia 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='Irudia 4')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Sortze data')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Edizio data')),
            ],
            options={
                'verbose_name': 'Bidaia',
                'verbose_name_plural': 'Bidaiak',
                'ordering': ['created'],
            },
        ),
    ]
