# Generated by Django 4.0.4 on 2022-05-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_mapblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Euskalmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Izena')),
                ('town', models.CharField(blank=True, max_length=200, null=True, verbose_name='Herria')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Deskribapena')),
                ('tempMax', models.FloatField(blank=True, null=True, verbose_name='temp max')),
                ('tempMin', models.FloatField(blank=True, null=True, verbose_name='temp min')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitudea')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitudea')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Sortze data')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Edizio data')),
            ],
            options={
                'verbose_name': 'Euskalmet',
                'verbose_name_plural': 'Euskalmet',
                'ordering': ['created'],
            },
        ),
    ]
