# Generated by Django 4.0.4 on 2022-05-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_euskalmet'),
    ]

    operations = [
        migrations.AddField(
            model_name='euskalmet',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Text'),
        ),
    ]
