# Generated by Django 4.0.4 on 2022-05-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_euskalmet_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenWeatherMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Izena')),
                ('owm', models.CharField(blank=True, max_length=200, null=True, verbose_name='code')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='webpath')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='Icon', verbose_name='Irudia 1')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Sortze data')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Edizio data')),
            ],
            options={
                'verbose_name': 'OpenWeatherMap',
                'verbose_name_plural': 'OpenWeatherMap',
                'ordering': ['created'],
            },
        ),
    ]
