# Generated by Django 4.0.4 on 2022-05-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_openweathermap_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbingspot',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='jatorria'),
        ),
    ]
