# Generated by Django 4.0.4 on 2022-06-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_climbingspot_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbingspot',
            name='locId',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='locId'),
        ),
        migrations.AddField(
            model_name='climbingspot',
            name='regionId',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='regioId'),
        ),
        migrations.AddField(
            model_name='climbingspot',
            name='zoneId',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='zoneId'),
        ),
    ]
