# Generated by Django 4.0.4 on 2022-06-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_openweathermap_euskalmet_alter_climbingspot_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='openweathermap',
            name='euskalmet_new',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='euskalmet icon new'),
        ),
    ]
